// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: expenses/v1/eps_grpc_api.proto

package v1

import (
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeriodicityType int32

const (
	PeriodicityType_PERIODICITY_TYPE_DAY_UNSPECIFIED PeriodicityType = 0
	PeriodicityType_PERIODICITY_TYPE_DAY_OF_WEEK     PeriodicityType = 1
	PeriodicityType_PERIODICITY_TYPE_WEEK            PeriodicityType = 2
	PeriodicityType_PERIODICITY_TYPE_MONTH           PeriodicityType = 3
	PeriodicityType_PERIODICITY_TYPE_QUARTER         PeriodicityType = 4
	PeriodicityType_PERIODICITY_TYPE_HALF_A_YEAR     PeriodicityType = 5
	PeriodicityType_PERIODICITY_TYPE_YEAR            PeriodicityType = 6
)

// Enum value maps for PeriodicityType.
var (
	PeriodicityType_name = map[int32]string{
		0: "PERIODICITY_TYPE_DAY_UNSPECIFIED",
		1: "PERIODICITY_TYPE_DAY_OF_WEEK",
		2: "PERIODICITY_TYPE_WEEK",
		3: "PERIODICITY_TYPE_MONTH",
		4: "PERIODICITY_TYPE_QUARTER",
		5: "PERIODICITY_TYPE_HALF_A_YEAR",
		6: "PERIODICITY_TYPE_YEAR",
	}
	PeriodicityType_value = map[string]int32{
		"PERIODICITY_TYPE_DAY_UNSPECIFIED": 0,
		"PERIODICITY_TYPE_DAY_OF_WEEK":     1,
		"PERIODICITY_TYPE_WEEK":            2,
		"PERIODICITY_TYPE_MONTH":           3,
		"PERIODICITY_TYPE_QUARTER":         4,
		"PERIODICITY_TYPE_HALF_A_YEAR":     5,
		"PERIODICITY_TYPE_YEAR":            6,
	}
)

func (x PeriodicityType) Enum() *PeriodicityType {
	p := new(PeriodicityType)
	*p = x
	return p
}

func (x PeriodicityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeriodicityType) Descriptor() protoreflect.EnumDescriptor {
	return file_expenses_v1_eps_grpc_api_proto_enumTypes[0].Descriptor()
}

func (PeriodicityType) Type() protoreflect.EnumType {
	return &file_expenses_v1_eps_grpc_api_proto_enumTypes[0]
}

func (x PeriodicityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeriodicityType.Descriptor instead.
func (PeriodicityType) EnumDescriptor() ([]byte, []int) {
	return file_expenses_v1_eps_grpc_api_proto_rawDescGZIP(), []int{0}
}

type ExpenseInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Date          *string                `protobuf:"bytes,2,opt,name=date" json:"date,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseInstance) Reset() {
	*x = ExpenseInstance{}
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseInstance) ProtoMessage() {}

func (x *ExpenseInstance) ProtoReflect() protoreflect.Message {
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseInstance.ProtoReflect.Descriptor instead.
func (*ExpenseInstance) Descriptor() ([]byte, []int) {
	return file_expenses_v1_eps_grpc_api_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseInstance) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ExpenseInstance) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

type Periodicity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *PeriodicityType       `protobuf:"varint,1,opt,name=type,enum=expenses.v1.PeriodicityType" json:"type,omitempty"`
	Frequency     *int32                 `protobuf:"varint,2,opt,name=frequency" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Periodicity) Reset() {
	*x = Periodicity{}
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Periodicity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Periodicity) ProtoMessage() {}

func (x *Periodicity) ProtoReflect() protoreflect.Message {
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Periodicity.ProtoReflect.Descriptor instead.
func (*Periodicity) Descriptor() ([]byte, []int) {
	return file_expenses_v1_eps_grpc_api_proto_rawDescGZIP(), []int{1}
}

func (x *Periodicity) GetType() PeriodicityType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return PeriodicityType_PERIODICITY_TYPE_DAY_UNSPECIFIED
}

func (x *Periodicity) GetFrequency() int32 {
	if x != nil && x.Frequency != nil {
		return *x.Frequency
	}
	return 0
}

type PlanExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	StartDate     *string                `protobuf:"bytes,3,opt,name=start_date,json=startDate" json:"start_date,omitempty"` // ISO 8601
	EndDate       *string                `protobuf:"bytes,4,opt,name=end_date,json=endDate" json:"end_date,omitempty"`       // ISO 8601
	Amount        *money.Money           `protobuf:"bytes,5,opt,name=amount" json:"amount,omitempty"`
	Periodicity   *Periodicity           `protobuf:"bytes,6,opt,name=periodicity" json:"periodicity,omitempty"`
	Instances     []*ExpenseInstance     `protobuf:"bytes,7,rep,name=instances" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanExpenseResponse) Reset() {
	*x = PlanExpenseResponse{}
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExpenseResponse) ProtoMessage() {}

func (x *PlanExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExpenseResponse.ProtoReflect.Descriptor instead.
func (*PlanExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expenses_v1_eps_grpc_api_proto_rawDescGZIP(), []int{2}
}

func (x *PlanExpenseResponse) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PlanExpenseResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PlanExpenseResponse) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *PlanExpenseResponse) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *PlanExpenseResponse) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PlanExpenseResponse) GetPeriodicity() *Periodicity {
	if x != nil {
		return x.Periodicity
	}
	return nil
}

func (x *PlanExpenseResponse) GetInstances() []*ExpenseInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type PlanExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	StartDate     *string                `protobuf:"bytes,2,opt,name=start_date,json=startDate" json:"start_date,omitempty"` // ISO 8601
	EndDate       *string                `protobuf:"bytes,3,opt,name=end_date,json=endDate" json:"end_date,omitempty"`       // ISO 8601
	Amount        *money.Money           `protobuf:"bytes,4,opt,name=amount" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanExpenseRequest) Reset() {
	*x = PlanExpenseRequest{}
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExpenseRequest) ProtoMessage() {}

func (x *PlanExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expenses_v1_eps_grpc_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExpenseRequest.ProtoReflect.Descriptor instead.
func (*PlanExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expenses_v1_eps_grpc_api_proto_rawDescGZIP(), []int{3}
}

func (x *PlanExpenseRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PlanExpenseRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *PlanExpenseRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *PlanExpenseRequest) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_expenses_v1_eps_grpc_api_proto protoreflect.FileDescriptor

const file_expenses_v1_eps_grpc_api_proto_rawDesc = "" +
	"\n" +
	"\x1eexpenses/v1/eps_grpc_api.proto\x12\vexpenses.v1\x1a\x17google/type/money.proto\"5\n" +
	"\x0fExpenseInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"]\n" +
	"\vPeriodicity\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.expenses.v1.PeriodicityTypeR\x04type\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x05R\tfrequency\"\x9e\x02\n" +
	"\x13PlanExpenseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12*\n" +
	"\x06amount\x18\x05 \x01(\v2\x12.google.type.MoneyR\x06amount\x12A\n" +
	"\vperiodicity\x18\x06 \x01(\v2\x18.expenses.v1.PeriodicityB\x05\xaa\x01\x02\b\x01R\vperiodicity\x12:\n" +
	"\tinstances\x18\a \x03(\v2\x1c.expenses.v1.ExpenseInstanceR\tinstances\"\x8e\x01\n" +
	"\x12PlanExpenseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.google.type.MoneyR\x06amount*\xeb\x01\n" +
	"\x0fPeriodicityType\x12$\n" +
	" PERIODICITY_TYPE_DAY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPERIODICITY_TYPE_DAY_OF_WEEK\x10\x01\x12\x19\n" +
	"\x15PERIODICITY_TYPE_WEEK\x10\x02\x12\x1a\n" +
	"\x16PERIODICITY_TYPE_MONTH\x10\x03\x12\x1c\n" +
	"\x18PERIODICITY_TYPE_QUARTER\x10\x04\x12 \n" +
	"\x1cPERIODICITY_TYPE_HALF_A_YEAR\x10\x05\x12\x19\n" +
	"\x15PERIODICITY_TYPE_YEAR\x10\x062b\n" +
	"\x0eExpenseService\x12P\n" +
	"\vPlanExpense\x12\x1f.expenses.v1.PlanExpenseRequest\x1a .expenses.v1.PlanExpenseResponseB/Z-github.com/ipasxa/eps-grpc-schema/expenses/v1b\beditionsp\xe8\a"

var (
	file_expenses_v1_eps_grpc_api_proto_rawDescOnce sync.Once
	file_expenses_v1_eps_grpc_api_proto_rawDescData []byte
)

func file_expenses_v1_eps_grpc_api_proto_rawDescGZIP() []byte {
	file_expenses_v1_eps_grpc_api_proto_rawDescOnce.Do(func() {
		file_expenses_v1_eps_grpc_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expenses_v1_eps_grpc_api_proto_rawDesc), len(file_expenses_v1_eps_grpc_api_proto_rawDesc)))
	})
	return file_expenses_v1_eps_grpc_api_proto_rawDescData
}

var file_expenses_v1_eps_grpc_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_expenses_v1_eps_grpc_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_expenses_v1_eps_grpc_api_proto_goTypes = []any{
	(PeriodicityType)(0),        // 0: expenses.v1.PeriodicityType
	(*ExpenseInstance)(nil),     // 1: expenses.v1.ExpenseInstance
	(*Periodicity)(nil),         // 2: expenses.v1.Periodicity
	(*PlanExpenseResponse)(nil), // 3: expenses.v1.PlanExpenseResponse
	(*PlanExpenseRequest)(nil),  // 4: expenses.v1.PlanExpenseRequest
	(*money.Money)(nil),         // 5: google.type.Money
}
var file_expenses_v1_eps_grpc_api_proto_depIdxs = []int32{
	0, // 0: expenses.v1.Periodicity.type:type_name -> expenses.v1.PeriodicityType
	5, // 1: expenses.v1.PlanExpenseResponse.amount:type_name -> google.type.Money
	2, // 2: expenses.v1.PlanExpenseResponse.periodicity:type_name -> expenses.v1.Periodicity
	1, // 3: expenses.v1.PlanExpenseResponse.instances:type_name -> expenses.v1.ExpenseInstance
	5, // 4: expenses.v1.PlanExpenseRequest.amount:type_name -> google.type.Money
	4, // 5: expenses.v1.ExpenseService.PlanExpense:input_type -> expenses.v1.PlanExpenseRequest
	3, // 6: expenses.v1.ExpenseService.PlanExpense:output_type -> expenses.v1.PlanExpenseResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_expenses_v1_eps_grpc_api_proto_init() }
func file_expenses_v1_eps_grpc_api_proto_init() {
	if File_expenses_v1_eps_grpc_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expenses_v1_eps_grpc_api_proto_rawDesc), len(file_expenses_v1_eps_grpc_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expenses_v1_eps_grpc_api_proto_goTypes,
		DependencyIndexes: file_expenses_v1_eps_grpc_api_proto_depIdxs,
		EnumInfos:         file_expenses_v1_eps_grpc_api_proto_enumTypes,
		MessageInfos:      file_expenses_v1_eps_grpc_api_proto_msgTypes,
	}.Build()
	File_expenses_v1_eps_grpc_api_proto = out.File
	file_expenses_v1_eps_grpc_api_proto_goTypes = nil
	file_expenses_v1_eps_grpc_api_proto_depIdxs = nil
}
