---
name: Lint

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Lint YAML
        uses: karancode/yamllint-github-action@v2.1.1

      - name: Setup Protolint
        # yamllint disable rule:line-length
        run: |
          wget --quiet https://github.com/yoheimuta/protolint/releases/download/v${PROTOLINT_VERSION}/protolint_${PROTOLINT_VERSION}_linux_amd64.tar.gz \
            && tar xf protolint_${PROTOLINT_VERSION}_linux_amd64.tar.gz \
            && chmod +x protolint \
            && mv protolint /usr/local/bin/protolint
        env:
          PROTOLINT_VERSION: 0.56.4

      - name: Lint Protobuf
        run: protolint .
